graalvm_file_id: "1xrxfMiLBWOS2ptPOnUClHrNXOuozid_a"
versions_file_id: "1_JH04cXYbWSbhTmn3Y9jQFAf57DayWNM"
python_portable_file_id: "1YyD9-wLDuFIu5Z0O38PHF9I6iIDAt5oO"
tlauncher_url: "https://dl1.tlauncher.org/f.php?f=files%2FTLauncher-Installer-1.9.5.1.exe"
java_dest_root: "C:\\Java"
otp_timeout_seconds: 15
